### ISSUE TITLE
Jumbled/unclear explanation in Method Scope (Programming as Conversation pt3) reading

### ISSUE THREAD

**Issue by theoluyi** [learn-co-curriculum/programming-univbasics-3-introduction#5]
This paragraph explaining scope within a method is unclear:

"Now if you run this code in IRB, you will see the out*put* "Hello World!". But even if you didn't use puts on local_variable, for a brief second, as my_ruby_method the variable would exist in the method's local scope."

I think it means to say * local_variable*  "would exist in the method's local scope."
At present the way it's written is confusing.

**Comment by maxwellbenton** [comment]
Hi @theoluyi,

Thank you for spotting this and providing feedback. Your issue helped us identify a problem that was preventing this lesson from updating. We've resolved the problem and updated the Readme, which should resolve this issue.

Thank you for contributing to a Learn lesson!
